name: rpa-project
services:
  rbas-db:
    image: postgres:11
    ports:
      - 5432
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=pgdb
    resources:
      cpu: 100m
      memory: 128Mi
  
  rpa-project:
    public: true
    image: gabrielb47/rpa-project:latest
    build: .
    replicas: 1
    command: bash -c "gunicorn rpa_project.wsgi --reload -b 0.0.0.0:8000"
    ports:
      - 8000
    resources:
      cpu: 100m
      memory: 128Mi
    environment:
        - DATABASE_URL=postgresql://pguser:pgpass@notes-db:5432/pgdb
        - COOKIE_SECURE=true
        - DEBUG=false